  spring:
    main:
      allow-circular-references: true
    datasource:
      url: jdbc:${DATABASE_PATH}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
    flyway:
      enabled: true
  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.ws: DEBUG
  server:
    hostname: localhost
    port: ${PORT:8080}
  mail:
    server:
      host: smtp.gmail.com
      port: 587
      username: alexey041187@gmail.com
      password: ${hidden.email.password}